"""delete ip-address in studentSession

Revision ID: 2fa2b591fc49
Revises: d067429d45f2
Create Date: 2026-05-22 09:58:15.698117
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa2b591fc49'
down_revision = 'd067429d45f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_session', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_session', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
