"""added student group

Revision ID: 3b5cba59b0fc
Revises: 9742dc196ff2
Create Date: 2026-06-05 11:33:39.036609
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = '3b5cba59b0fc'
down_revision = '9742dc196ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'student', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'group')
    # ### end Alembic commands ###
