"""added email notification and itis schedule

Revision ID: 5fbdaa4497ea
Revises: 3b5cba59b0fc
Create Date: 2026-06-06 11:29:49.480953
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '5fbdaa4497ea'
down_revision = '3b5cba59b0fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itis_schedule',
    sa.Column('day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('time_slot', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('lesson_details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itis_schedule_group'), 'itis_schedule', ['group'], unique=False)
    op.create_table('email_notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('VERIFY_EMAIL', 'CHANGE_PASSWORD', name='emailaction'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='emailstatus'), nullable=False),
    sa.Column('code', sa.Uuid(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_notification_student_id'), 'email_notification', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_notification_student_id'), table_name='email_notification')
    op.drop_table('email_notification')
    op.drop_index(op.f('ix_itis_schedule_group'), table_name='itis_schedule')
    op.drop_table('itis_schedule')
    # ### end Alembic commands ###
