"""add email notification table and is_email_verificated into student table 

Revision ID: 9742dc196ff2
Revises: 2fa2b591fc49
Create Date: 2026-06-01 13:36:57.927475
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9742dc196ff2'
down_revision = '2fa2b591fc49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('is_email_verificated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'is_email_verificated')
    # ### end Alembic commands ###
