"""your_message

Revision ID: a5528edf7870
Revises: a0e51b9d2a08
Create Date: 2026-03-23 12:36:06.050287
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5528edf7870'
down_revision = 'a0e51b9d2a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
