"""comment

Revision ID: c5b401dce71a
Revises: f1313f5bf38c
Create Date: 2026-04-30 10:16:42.367449
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b401dce71a'
down_revision = 'f1313f5bf38c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
